import smtplib, os
from email.message import EmailMessage

def send_to_patient_leads():
    # Path to the leads generated by our hunter agent
    if not os.path.exists('patient_leads.txt'):
        print("No leads found yet.")
        return

    with open('patient_leads.txt', 'r') as f:
        content = f.read().split('---')

    for lead in content:
        if "TARGET:" in lead:
            target = lead.split('TARGET:')[1].split('\n')[0].strip()
            body = lead.split('Subject:')[1]
            subject = "Clinical Partnership Proposal - Dr. Abhishek Bansal"

            msg = EmailMessage()
            msg.set_content(body)
            msg['Subject'] = subject
            msg['From'] = "bansallab@outlook.com"
            msg['To'] = target

            try:
                with smtplib.SMTP('smtp.office365.com', 587) as server:
                    server.starttls()
                    server.login("bansallab@outlook.com", os.environ['OUTLOOK_APP_PASSWORD'])
                    server.send_message(msg)
                    print(f"✅ Patient lead sent to: {target}")
            except Exception as e:
                print(f"❌ Error sending to {target}: {e}")

if __name__ == "__main__":
    send_to_patient_leads()
