import os
import google.oauth2.credentials
import google_auth_oauthlib.flow
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

def get_service():
    creds = google.oauth2.credentials.Credentials(
        None,
        refresh_token=os.environ.get('NEW_YT_REFRESH_TOKEN'),
        token_uri="https://oauth2.googleapis.com/token",
        client_id=os.environ.get('NEW_YT_CLIENT_ID'),
        client_secret=os.environ.get('NEW_YT_CLIENT_SECRET')
    )
    return build('youtube', 'v3', credentials=creds)

def upload_video():
    youtube = get_service()
    
    # Path to the video generated by Manim
    video_path = "media/videos/music_gen/1080p60/NeonLyrics.mp4"
    
    body = {
        'snippet': {
            'title': 'Soulful AI Melodies #Shorts #Romantic',
            'description': 'Automated AI Romantic Vibes. Made with Love and Code.',
            'tags': ['Romantic', 'AISongs', 'Shorts'],
            'categoryId': '10' # Music category
        },
        'status': {
            'privacyStatus': 'public',
            'selfDeclaredMadeForKids': False
        }
    }

    insert_request = youtube.videos().insert(
        part='snippet,status',
        body=body,
        media_body=MediaFileUpload(video_path, chunksize=-1, resumable=True)
    )
    
    response = insert_request.execute()
    print(f"Success! Video ID: {response['id']}")

if __name__ == "__main__":
    upload_video()
